version: '3'
services:
  api-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/app/api
    command: tail -f /dev/null
    
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
