GET http://localhost:3333/tickets

###
POST http://localhost:3333/tickets
Content-Type: application/json

{
  "product": 1, 
  "codTransporter": 1, 
  "ticket": 125, 
  "value": 123.50, 
  "weight": 60.10,
  "invoiced": true
}

###
GET http://localhost:3333/tickets-faturados

###
PUT http://localhost:3333/tickets-integrado
Content-Type: application/json

{
  "id": "cloi0jjb20000tattqvfadyv8"
}